version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
     - "27017:27017"
    volumes:
     - "./data:/data/db"
  web:
    build: .
    ports:
     - "8080:8080"
    depends_on:
     - mongodb
    links:
     - "mongodb:mongodb"
    environment:
     - "MONGO_URL=mongodb://mongodb:27017"